### ISSUE TITLE
ImportError: cannot import name initialize_db

### ISSUE THREAD

**Issue by ionelmc** [dbaty/Poulda#2]
```
(ve) D:\Projects\upload-bucket>pserve dev.ini
Traceback (most recent call last):
  File "D:\Projects\upload-bucket\ve\Scripts\pserve-script.py", line 8, in <module>
    load_entry_point('pyramid==1.4.3', 'console_scripts', 'pserve')()
  File "D:\Projects\upload-bucket\ve\lib\site-packages\pyramid\scripts\pserve.py", line 50, in main
    return command.run()
  File "D:\Projects\upload-bucket\ve\lib\site-packages\pyramid\scripts\pserve.py", line 304, in run
    global_conf=vars)
  File "D:\Projects\upload-bucket\ve\lib\site-packages\pyramid\scripts\pserve.py", line 328, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "D:\Projects\upload-bucket\ve\lib\site-packages\paste\deploy\loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "D:\Projects\upload-bucket\ve\lib\site-packages\paste\deploy\loadwsgi.py", line 272, in loadobj
    return context.create()
  File "D:\Projects\upload-bucket\ve\lib\site-packages\paste\deploy\loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "D:\Projects\upload-bucket\ve\lib\site-packages\paste\deploy\loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "D:\Projects\upload-bucket\ve\lib\site-packages\paste\deploy\util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "D:\Projects\upload-bucket\ve\lib\site-packages\poulda\app.py", line 15, in make_app
    from poulda.models import initialize_db
ImportError: cannot import name initialize_db
```

**Comment by ionelmc** [comment]
`dev.ini` is a copy of https://raw.github.com/dbaty/poulda/master/development.ini

**Comment by dbaty** [comment]
The default `development.ini` configuration does not use Nginx Upload Progress module and hence requires a database. You should therefore install Poulda with its database-related requirements, which seems lacking according to the error message. As indicated in the documentation, this is done with the following `easy_install` command:

```
easy_install Poulda[db]
```
